"""Evidence packet: an indexed, bookmarked PDF containing the exact source
pages that support each claimed condition, prefixed by an index that maps
condition → exhibits. Source pages are stamped with exhibit numbers."""

from __future__ import annotations

import io

from pypdf import PdfReader, PdfWriter
from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from sqlalchemy import select

from .. import models, schemas

W, H = letter


def _collect(db, case_id: int):
    """conditions → their evidence (doc, page) refs; and the unique exhibit
    list in stable order."""
    conditions = db.scalars(
        select(models.Condition)
        .where(models.Condition.case_id == case_id,
               models.Condition.status.in_(["selected", "claimed"]))
        .order_by(models.Condition.sort, models.Condition.id)).all()
    events = db.scalars(select(models.MedicalEvent)
                        .where(models.MedicalEvent.case_id == case_id)).all()

    per_condition: list[dict] = []
    exhibits: dict[tuple[int, int], int] = {}  # (doc_id, page_no) → exhibit no
    for cond in conditions:
        key = cond.name.lower().split(",")[0].split("(")[0].strip()
        evs = [e for e in events
               if key and (key in e.condition.lower() or e.condition.lower() in key)]
        items = []
        for e in sorted(evs, key=lambda e: (e.date or "9999")):
            ref = (e.document_id, e.page_no)
            if ref not in exhibits:
                exhibits[ref] = len(exhibits) + 1
            doc = db.get(models.Document, e.document_id)
            items.append({"exhibit": exhibits[ref], "date": e.date,
                          "kind": e.kind, "detail": e.detail,
                          "filename": doc.filename if doc else "?",
                          "page_no": e.page_no})
        per_condition.append({"condition": cond, "items": items})
    return per_condition, exhibits


def _index_pdf(veteran: str, per_condition: list[dict]) -> PdfReader:
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)

    def header(title: str):
        c.setFillColor(HexColor("#1b2a4a"))
        c.setFont("Helvetica-Bold", 15)
        c.drawString(54, H - 60, title)
        c.setFillColor(HexColor("#444444"))
        c.setFont("Helvetica", 9)
        c.drawString(54, H - 76, f"Claimant: {veteran}")
        c.drawString(54, H - 88,
                     "Evidence index generated by VetClaims Local — review before filing. "
                     "Exhibit numbers refer to pages later in this document.")
        c.line(54, H - 94, W - 54, H - 94)
        return H - 116

    y = header("Evidence Index")
    for group in per_condition:
        cond = group["condition"]
        if y < 120:
            c.showPage()
            y = header("Evidence Index (continued)")
        c.setFillColor(HexColor("#000000"))
        c.setFont("Helvetica-Bold", 11)
        label = cond.name + (f"  (secondary to {cond.secondary_to})"
                             if cond.secondary_to else "")
        c.drawString(54, y, label)
        y -= 15
        c.setFont("Helvetica", 9)
        if not group["items"]:
            c.setFillColor(HexColor("#8a6d1a"))
            c.drawString(66, y, "No documentary evidence located in uploaded records "
                                "— rely on statements / new medical evidence.")
            y -= 14
        for item in group["items"]:
            if y < 90:
                c.showPage()
                y = header("Evidence Index (continued)")
                c.setFont("Helvetica", 9)
            c.setFillColor(HexColor("#000000"))
            text = (f"Exhibit {item['exhibit']:>2}  ·  {item['date'] or 'undated'}  ·  "
                    f"{item['kind']}  ·  {item['detail'][:80]}")
            c.drawString(66, y, text)
            c.setFillColor(HexColor("#666666"))
            c.drawString(66, y - 10, f"           source: {item['filename']} p.{item['page_no']}")
            y -= 24
        y -= 8
    c.showPage()
    c.save()
    buf.seek(0)
    return PdfReader(buf)


def _stamp(exhibit_no: int) -> PdfReader:
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    c.setFillColor(HexColor("#b00020"))
    c.setFont("Helvetica-Bold", 10)
    c.drawRightString(W - 36, H - 24, f"EXHIBIT {exhibit_no}")
    c.showPage()
    c.save()
    buf.seek(0)
    return PdfReader(buf)


def build_evidence_pdf(db, case_id: int) -> bytes:
    profile_row = db.scalars(select(models.ClaimantProfile)
                             .where(models.ClaimantProfile.case_id == case_id)).first()
    profile = schemas.ClaimantProfileData.model_validate(
        profile_row.data if profile_row else {})
    veteran = (f"{profile.identity.first_name} {profile.identity.last_name}".strip()
               or "Veteran")

    per_condition, exhibits = _collect(db, case_id)
    writer = PdfWriter()

    index = _index_pdf(veteran, per_condition)
    for page in index.pages:
        writer.add_page(page)
    n_index = len(index.pages)
    writer.add_outline_item("Evidence index", 0)

    # append exhibit pages in exhibit order, stamped
    page_of_exhibit: dict[int, int] = {}
    readers: dict[int, PdfReader] = {}
    for (doc_id, page_no), exhibit_no in sorted(exhibits.items(), key=lambda kv: kv[1]):
        doc = db.get(models.Document, doc_id)
        if doc is None:
            continue
        if doc_id not in readers:
            readers[doc_id] = PdfReader(doc.stored_path)
        src = readers[doc_id].pages[page_no - 1]
        src.merge_page(_stamp(exhibit_no).pages[0])
        writer.add_page(src)
        page_of_exhibit[exhibit_no] = n_index + len(page_of_exhibit)

    # bookmarks per condition pointing at their first exhibit
    for group in per_condition:
        if group["items"]:
            first = min(i["exhibit"] for i in group["items"])
            writer.add_outline_item(group["condition"].name,
                                    page_of_exhibit[first])

    out = io.BytesIO()
    writer.write(out)
    return out.getvalue()
